version: '3'

services:

  'mysql':
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: techie
      MYSQL_DATABASE: mrcore5
      MYSQL_USER: root
      MYSQL_PASSWORD: techie
    networks:
      - frontend
    ports:
      - "3306:3306"

  'redis':
    image: redis:4.0
    container_name: redis
    networks:
      - frontend
    ports:
      - "6379:6379"

networks:
  frontend:

