version: '3'

services:

  'mreschke-mrcore-laravel58-app':
    image: mreschke/laravel:5.8
    container_name: mreschke-mrcore-laravel58-app
    working_dir: /root/Code/mreschke/php/mrcore-laravel58-app

    # Map ports (host:container)
    networks:
      - frontend
    ports:
        - "${DOCKER_PHP_PORT}:${DOCKER_PHP_PORT}"
        #- 8081:8081 # For event system server.js socketio server not work, CORS issues

    # Mount host volumes (host:container)
    volumes:
      - ${DOCKER_CODE_BASE}:/root/Code
      - ~/.composer:/root/.composer # To use hosts composer cache

    # Run command
    command: php artisan serve --port=${DOCKER_PHP_PORT} --host=0.0.0.0

networks:
  frontend:

