#!/bin/bash

# Service name as defined in your docker-compose.yml (not container name, but service name)
service="mysql"

#echo "Executing Command Inside Running Container..."; echo # No echo as it gets in the way of dumps
base="$( cd "$(dirname "$0")" ; cd ..; pwd -P )"; cd $base
docker-compose exec $service mysqldump "$@"

