#!/bin/bash

# Service name as defined in your docker-compose.yml (not container name, but service name)
service="web"

echo "Running Command In a NEW Separate Container..."; echo
base="$( cd "$(dirname "$0")" ; cd ..; pwd -P )"; cd $base
docker-compose run --rm $service "$@"

